name: compile

on:
  push:
    branches: [ main, development ]
    paths:
      - 'src/**'
      - '.github/workflows/compile.yml'

  pull_request:
    branches: [ main, development ]
    paths:
      - 'src/**'
      - '.github/workflows/compile.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: compile
      working-directory: src
      run: |
        npm ci
        npm run build --if-present
